"""phase3 market data normalization

Revision ID: 8c297f23101e
Revises: 20260828_0001
Create Date: 2026-08-28 16:48:12.178590
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "8c297f23101e"
down_revision: str | None = "20260828_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "canonical_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("league", sa.String(length=32), nullable=False),
        sa.Column("home_team", sa.String(length=200), nullable=False),
        sa.Column("away_team", sa.String(length=200), nullable=False),
        sa.Column("scheduled_start_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("event_status", sa.String(length=32), nullable=False),
        sa.Column("match_confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("review_status", sa.String(length=32), nullable=False),
        sa.Column(
            "match_provenance",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "review_status IN ('matched', 'needs_review', 'conflict')",
            name=op.f("ck_canonical_events_event_review_status"),
        ),
        sa.CheckConstraint(
            "match_confidence >= 0 AND match_confidence <= 1", name=op.f("ck_canonical_events_event_match_confidence")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_canonical_events")),
    )
    op.create_index(
        "ix_canonical_events_league_start", "canonical_events", ["league", "scheduled_start_utc"], unique=False
    )
    op.create_table(
        "market_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider_name", sa.String(length=64), nullable=False),
        sa.Column("provider_sport_key", sa.String(length=100), nullable=False),
        sa.Column("canonical_league", sa.String(length=32), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("provider_retrieved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "request_parameters",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "raw_payload", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        sa.Column(
            "response_metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("ingestion_status", sa.String(length=32), nullable=False),
        sa.Column(
            "warning_metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "error_metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "ingestion_status IN ('success', 'partial', 'failed')", name=op.f("ck_market_snapshots_ingestion_status")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_snapshots")),
    )
    op.create_index(
        "ix_market_snapshots_provider_league_requested",
        "market_snapshots",
        ["provider_name", "canonical_league", "requested_at"],
        unique=False,
    )
    op.create_table(
        "sportsbooks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("canonical_key", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sportsbooks")),
        sa.UniqueConstraint("canonical_key", name=op.f("uq_sportsbooks_canonical_key")),
    )
    op.create_table(
        "provider_event_mappings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider_name", sa.String(length=64), nullable=False),
        sa.Column("provider_sport_key", sa.String(length=100), nullable=False),
        sa.Column("provider_event_id", sa.String(length=200), nullable=False),
        sa.Column("canonical_event_id", sa.Uuid(), nullable=False),
        sa.Column("match_confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("review_status", sa.String(length=32), nullable=False),
        sa.Column(
            "provenance", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "review_status IN ('matched', 'needs_review', 'conflict')",
            name=op.f("ck_provider_event_mappings_mapping_review_status"),
        ),
        sa.CheckConstraint(
            "match_confidence >= 0 AND match_confidence <= 1",
            name=op.f("ck_provider_event_mappings_mapping_match_confidence"),
        ),
        sa.ForeignKeyConstraint(
            ["canonical_event_id"],
            ["canonical_events.id"],
            name=op.f("fk_provider_event_mappings_canonical_event_id_canonical_events"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_event_mappings")),
        sa.UniqueConstraint(
            "provider_name",
            "provider_sport_key",
            "provider_event_id",
            "canonical_event_id",
            name="uq_provider_event_candidate",
        ),
    )
    op.create_index(
        "ix_provider_event_lookup",
        "provider_event_mappings",
        ["provider_name", "provider_sport_key", "provider_event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_provider_event_mappings_canonical_event_id"),
        "provider_event_mappings",
        ["canonical_event_id"],
        unique=False,
    )
    op.create_table(
        "provider_sportsbooks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider_name", sa.String(length=64), nullable=False),
        sa.Column("provider_identifier", sa.String(length=200), nullable=False),
        sa.Column("provider_display_name", sa.String(length=200), nullable=False),
        sa.Column("sportsbook_id", sa.Uuid(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["sportsbook_id"],
            ["sportsbooks.id"],
            name=op.f("fk_provider_sportsbooks_sportsbook_id_sportsbooks"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_sportsbooks")),
        sa.UniqueConstraint("provider_name", "provider_identifier", name="uq_provider_sportsbook_identifier"),
    )
    op.create_index(
        op.f("ix_provider_sportsbooks_sportsbook_id"), "provider_sportsbooks", ["sportsbook_id"], unique=False
    )
    op.create_table(
        "market_observations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("sportsbook_id", sa.Uuid(), nullable=False),
        sa.Column("provider_sportsbook_id", sa.Uuid(), nullable=False),
        sa.Column("market_type", sa.String(length=32), nullable=False),
        sa.Column("period", sa.String(length=32), nullable=False),
        sa.Column("selection_side", sa.String(length=32), nullable=False),
        sa.Column("selection_name", sa.String(length=300), nullable=False),
        sa.Column("point", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("point_key", sa.String(length=32), nullable=False),
        sa.Column("american_odds", sa.Integer(), nullable=False),
        sa.Column("provider_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observation_age_seconds", sa.Integer(), nullable=True),
        sa.Column("freshness_policy_version", sa.String(length=64), nullable=False),
        sa.Column("stale_after_seconds", sa.Integer(), nullable=False),
        sa.Column("is_stale", sa.Boolean(), nullable=False),
        sa.Column("observation_status", sa.String(length=32), nullable=False),
        sa.Column("match_review_status", sa.String(length=32), nullable=False),
        sa.Column(
            "raw_source", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "market_type IN ('moneyline', 'spread', 'total')",
            name=op.f("ck_market_observations_observation_market_type"),
        ),
        sa.CheckConstraint(
            "match_review_status IN ('matched', 'needs_review', 'conflict')",
            name=op.f("ck_market_observations_match_review_status"),
        ),
        sa.CheckConstraint(
            "observation_status IN ('active', 'suspended')", name=op.f("ck_market_observations_observation_status")
        ),
        sa.CheckConstraint("period IN ('full_game')", name=op.f("ck_market_observations_observation_period")),
        sa.CheckConstraint(
            "selection_side IN ('home', 'away', 'draw', 'over', 'under')",
            name=op.f("ck_market_observations_selection_side"),
        ),
        sa.CheckConstraint(
            "american_odds <= -100 OR american_odds >= 100", name=op.f("ck_market_observations_american_odds_valid")
        ),
        sa.CheckConstraint(
            "(market_type = 'moneyline' AND point IS NULL AND point_key = 'none') OR "
            "(market_type IN ('spread', 'total') AND point IS NOT NULL AND point_key <> 'none')",
            name=op.f("ck_market_observations_observation_point_identity"),
        ),
        sa.CheckConstraint(
            "observation_age_seconds IS NULL OR observation_age_seconds >= 0",
            name=op.f("ck_market_observations_age_nonnegative"),
        ),
        sa.CheckConstraint("stale_after_seconds > 0", name=op.f("ck_market_observations_stale_after_positive")),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["canonical_events.id"],
            name=op.f("fk_market_observations_event_id_canonical_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["provider_sportsbook_id"],
            ["provider_sportsbooks.id"],
            name=op.f("fk_market_observations_provider_sportsbook_id_provider_sportsbooks"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["market_snapshots.id"],
            name=op.f("fk_market_observations_snapshot_id_market_snapshots"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sportsbook_id"],
            ["sportsbooks.id"],
            name=op.f("fk_market_observations_sportsbook_id_sportsbooks"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_observations")),
        sa.UniqueConstraint(
            "snapshot_id",
            "event_id",
            "sportsbook_id",
            "market_type",
            "period",
            "selection_side",
            "point_key",
            name="uq_market_observation_identity",
        ),
    )
    op.create_index(
        "ix_market_observation_lookup",
        "market_observations",
        ["event_id", "sportsbook_id", "market_type", "period", "selection_side", "point_key", "observed_at"],
        unique=False,
    )
    op.create_index(op.f("ix_market_observations_event_id"), "market_observations", ["event_id"], unique=False)
    op.create_index(op.f("ix_market_observations_snapshot_id"), "market_observations", ["snapshot_id"], unique=False)
    op.create_index(
        op.f("ix_market_observations_sportsbook_id"), "market_observations", ["sportsbook_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_market_observations_sportsbook_id"), table_name="market_observations")
    op.drop_index(op.f("ix_market_observations_snapshot_id"), table_name="market_observations")
    op.drop_index(op.f("ix_market_observations_event_id"), table_name="market_observations")
    op.drop_index("ix_market_observation_lookup", table_name="market_observations")
    op.drop_table("market_observations")
    op.drop_index(op.f("ix_provider_sportsbooks_sportsbook_id"), table_name="provider_sportsbooks")
    op.drop_table("provider_sportsbooks")
    op.drop_index(op.f("ix_provider_event_mappings_canonical_event_id"), table_name="provider_event_mappings")
    op.drop_index("ix_provider_event_lookup", table_name="provider_event_mappings")
    op.drop_table("provider_event_mappings")
    op.drop_table("sportsbooks")
    op.drop_index("ix_market_snapshots_provider_league_requested", table_name="market_snapshots")
    op.drop_table("market_snapshots")
    op.drop_index("ix_canonical_events_league_start", table_name="canonical_events")
    op.drop_table("canonical_events")
    # ### end Alembic commands ###
