import { CircleDollarSign } from "lucide-react";
import { useMemo, useState } from "react";
import { EmptyState, ErrorPage, LoadingPage, PageHeader, Panel, StatusBadge } from "../components/Primitives";
import { useDashboard, useRecommendationAction } from "../hooks/useDashboard";
import { american, currency, formatDateTime, titleCase } from "../utils/format";

const tabs = ["Recommended", "Approved", "Open", "Settled", "Rejected"] as const;
export function BetsPage() {
  const query = useDashboard(); const action = useRecommendationAction(); const [tab, setTab] = useState<(typeof tabs)[number]>("Recommended");
  const rows = useMemo(() => { if (!query.data) return []; if (["Recommended", "Approved", "Rejected"].includes(tab)) return query.data.recommendations.filter((item) => item.status === ({ Recommended: "proposed", Approved: "approved", Rejected: "rejected" } as Record<string, string>)[tab]).map((item) => ({ id: item.recommendation_id, event: `${item.away_team} @ ${item.home_team}`, market: item.market, selection: item.selection, book: item.sportsbook, odds: item.odds, stake: item.stake, status: item.status, result: null, pnl: null, timestamp: String(item.provenance.as_of ?? ""), model: item.model_version, recommendation: true })); return query.data.portfolio.bets.filter((bet) => bet.status === tab.toLowerCase()).map((bet) => ({ id: bet.bet_id, event: `${bet.away_team ?? ""} @ ${bet.home_team ?? ""}`, market: bet.market_type, selection: bet.selection, book: bet.book, odds: bet.odds, stake: bet.stake, status: bet.status, result: bet.result, pnl: bet.payout, timestamp: bet.created_at, model: bet.model_version ?? "—", recommendation: false })); }, [query.data, tab]);
  if (query.isLoading) return <LoadingPage />; if (query.isError || !query.data) return <ErrorPage message={query.error?.message || "Bets unavailable"} retry={() => void query.refetch()} />;
  return <div className="page-stack"><PageHeader eyebrow="Execution book" title="Bets and approvals" description="Recommendations stay separate from official paper bets until explicit approval succeeds on the server." /><div className="tabs" role="tablist">{tabs.map((item) => <button role="tab" aria-selected={tab === item} className={tab === item ? "active" : ""} key={item} onClick={() => setTab(item)}>{item}</button>)}</div><Panel>{rows.length ? <div className="table-shell"><table><thead><tr><th>Event / selection</th><th>Market</th><th>Book</th><th>Odds</th><th>Stake</th><th>Status</th><th>Result</th><th>P&L</th><th>Model</th><th>Timestamp</th><th /></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><div className="pick-name"><strong>{row.selection}</strong><small>{row.event}</small></div></td><td>{titleCase(row.market)}</td><td>{titleCase(row.book)}</td><td>{american(row.odds)}</td><td>{currency(row.stake)}</td><td><StatusBadge tone={row.status === "rejected" ? "negative" : row.status === "settled" ? "neutral" : "info"}>{titleCase(row.status)}</StatusBadge></td><td>{titleCase(row.result)}</td><td className={(row.pnl ?? 0) >= 0 ? "positive-value" : "negative-value"}>{row.pnl == null ? "—" : currency(row.pnl)}</td><td className="mono compact">{row.model}</td><td>{row.timestamp ? formatDateTime(row.timestamp) : "—"}</td><td>{row.recommendation && row.status === "proposed" && <div className="inline-actions"><button className="button approve small" disabled={action.isPending} onClick={() => action.mutate({ id: row.id, action: "approve" })}>Approve</button><button className="button reject small" disabled={action.isPending} onClick={() => action.mutate({ id: row.id, action: "reject" })}>Reject</button></div>}</td></tr>)}</tbody></table></div> : <EmptyState icon={CircleDollarSign} title={`No ${tab.toLowerCase()} items`} body="This state is expected until the paper portfolio lifecycle reaches this stage." />}</Panel></div>;
}
