import { History } from "lucide-react";
import { useMemo, useState } from "react";
import { PerformanceBars } from "../components/Charts";
import { EmptyState, ErrorPage, LoadingPage, PageHeader, Panel, StatusBadge } from "../components/Primitives";
import { useDashboard } from "../hooks/useDashboard";
import { american, currency, formatDateTime, titleCase } from "../utils/format";

export function HistoryPage() { const query = useDashboard(); const [market, setMarket] = useState("all"); const [result, setResult] = useState("all"); const settled = useMemo(() => query.data?.portfolio.bets.filter((bet) => bet.status === "settled" && (market === "all" || bet.market_type === market) && (result === "all" || bet.result === result)) ?? [], [query.data, market, result]); if (query.isLoading) return <LoadingPage />; if (query.isError || !query.data) return <ErrorPage message={query.error?.message || "History unavailable"} retry={() => void query.refetch()} />; return <div className="page-stack"><PageHeader eyebrow="Settled book" title="Portfolio history" description="Immutable paper outcomes, execution context, and cumulative performance." /><div className="filters"><select aria-label="History market filter" value={market} onChange={(event) => setMarket(event.target.value)}><option value="all">All markets</option><option value="moneyline">Moneyline</option><option value="spread">Spread</option><option value="total">Total</option></select><select aria-label="History result filter" value={result} onChange={(event) => setResult(event.target.value)}><option value="all">All results</option><option value="win">Wins</option><option value="loss">Losses</option><option value="push">Pushes</option></select></div>
  <div className="dashboard-split"><Panel title="Cumulative result" eyebrow="Filtered history"><PerformanceBars data={settled.map((bet, index) => ({ name: `#${index + 1}`, pnl: bet.payout }))} /></Panel><Panel title="History snapshot" eyebrow="Current filter"><div className="history-summary"><div><strong>{settled.length}</strong><span>Settled bets</span></div><div><strong>{currency(settled.reduce((sum, bet) => sum + bet.payout, 0))}</strong><span>Realized P&amp;L</span></div><div><strong>{currency(settled.reduce((sum, bet) => sum + bet.stake, 0))}</strong><span>Turnover</span></div></div></Panel></div>
  <Panel>{settled.length ? <div className="table-shell"><table><thead><tr><th>Date</th><th>Event / selection</th><th>Market</th><th>Book</th><th>Odds</th><th>Stake</th><th>Result</th><th>P&L</th><th>Closing</th><th>Model</th></tr></thead><tbody>{settled.map((bet) => <tr key={bet.bet_id}><td>{formatDateTime(bet.created_at)}</td><td><div className="pick-name"><strong>{bet.selection}</strong><small>{bet.away_team} @ {bet.home_team}</small></div></td><td>{titleCase(bet.market_type)}</td><td>{titleCase(bet.book)}</td><td>{american(bet.odds)}</td><td>{currency(bet.stake)}</td><td><StatusBadge tone={bet.result === "win" ? "positive" : bet.result === "loss" ? "negative" : "neutral"}>{titleCase(bet.result)}</StatusBadge></td><td className={bet.payout >= 0 ? "positive-value" : "negative-value"}>{currency(bet.payout)}</td><td>{american(bet.closing_odds)}</td><td className="mono compact">{bet.model_version || "—"}</td></tr>)}</tbody></table></div> : <EmptyState icon={History} title="No settled history" body="Settled paper bets will appear here without changing their original recommendation context." />}</Panel></div>; }
