import { Clock3, TrendingUp } from "lucide-react";
import { MovementChart } from "../components/Charts";
import { EmptyState, ErrorPage, LoadingPage, PageHeader, Panel, StatusBadge } from "../components/Primitives";
import { useDashboard } from "../hooks/useDashboard";
import { american, formatDateTime, line, titleCase } from "../utils/format";

export function MarketMovementPage() { const query = useDashboard(); if (query.isLoading) return <LoadingPage />; if (query.isError || !query.data) return <ErrorPage message={query.error?.message || "Market movement unavailable"} retry={() => void query.refetch()} />; const { movement, recommendations } = query.data; return <div className="page-stack"><PageHeader eyebrow="Stored observations" title="Market movement" description="Line history comes from backend snapshots only. Dashboard refreshes do not call The Odds API." actions={<StatusBadge tone={query.data.system.stale ? "warning" : "positive"}>{query.data.system.stale ? "Stale" : "Fresh"}</StatusBadge>} />
    <div className="movement-summary"><span><Clock3 />Snapshot cutoff <strong>{formatDateTime(movement.as_of)}</strong></span><span>{movement.source_snapshot_count} source snapshots</span><span>{movement.events.length} games tracked</span></div>
    {movement.events.length ? movement.events.map((event) => { const latest = event.points.at(-1); const first = event.points[0]; const recommendation = recommendations.find((item) => item.event_id === event.event_id); return <Panel key={event.event_id} title={`${event.away_team} @ ${event.home_team}`} eyebrow={formatDateTime(event.scheduled_start)} action={recommendation ? <StatusBadge tone="positive">Recommended</StatusBadge> : undefined}><div className="movement-grid"><div className="movement-stats"><div><span>Opening line</span><strong>{event.opening_available ? line(first?.point) : "Unavailable"}</strong><small>Provider does not label true opener</small></div><div><span>First observed</span><strong>{line(first?.point)}</strong><small>{first ? formatDateTime(first.observed_at) : "—"}</small></div><div><span>Current stored</span><strong>{line(latest?.point)} <em>{american(latest?.american_odds)}</em></strong><small>{titleCase(latest?.sportsbook)}</small></div><div><span>Recommendation</span><strong>{recommendation ? `${line(recommendation.point)} ${american(recommendation.odds)}` : "No position"}</strong><small>{recommendation ? titleCase(recommendation.sportsbook) : "No qualified opportunity"}</small></div></div><MovementChart event={event} /></div></Panel>; }) : <Panel><EmptyState icon={TrendingUp} title="No stored movement for this slate" body="Run backend market ingestion to create auditable snapshots. Browser refreshes intentionally do not trigger provider calls." /></Panel>}
  </div>; }
