import { Activity, Ban, CheckCircle2, Microscope } from "lucide-react";
import { EmptyState, ErrorPage, LoadingPage, PageHeader, Panel, StatusBadge } from "../components/Primitives";
import { useDashboard } from "../hooks/useDashboard";
import { formatDateTime, titleCase } from "../utils/format";

const tone = (status: string) => status === "retained_benchmark" ? "positive" : status === "rejected" ? "negative" : "info";
export function ModelsPage() { const query = useDashboard(); if (query.isLoading) return <LoadingPage />; if (query.isError || !query.data) return <ErrorPage message={query.error?.message || "Registry unavailable"} retry={() => void query.refetch()} />; const models = query.data.system.models; const retained = models.filter((item) => item.status === "retained_benchmark"); return <div className="page-stack"><PageHeader eyebrow="NCAAF model registry" title="Fair-value authority" description="Registry status makes the benchmark supplying fair value explicit—and keeps diagnostic or rejected football models out of production decisions." />
    <Panel className="benchmark-banner"><div className="benchmark-content"><div className="benchmark-icon"><CheckCircle2 /></div><div><span className="eyebrow">Retained NCAAF v1 benchmark</span><h2>Market consensus powers fair value</h2><p>Moneyline, spread, margin, and total use the registered unweighted median consensus with proportional vig removal. Best executable price remains a separate input.</p></div><StatusBadge tone="positive">Retained benchmark</StatusBadge></div></Panel>
    {models.length ? <div className="model-grid">{models.map((model) => <Panel key={`${model.model_id}-${model.version}`} className="model-card"><div className="model-card-top"><div className={`model-icon ${model.status}`}>{model.status === "rejected" ? <Ban /> : model.status === "diagnostic" ? <Microscope /> : <Activity />}</div><StatusBadge tone={tone(model.status)}>{titleCase(model.status)}</StatusBadge></div><h3>{model.model_id}</h3><p>{model.promotion_decision}</p><dl><div><dt>Version</dt><dd>{model.version}</dd></div><div><dt>Market</dt><dd>{titleCase(model.market_type)}</dd></div><div><dt>Family</dt><dd>{titleCase(model.model_family)}</dd></div><div><dt>Holdout</dt><dd>{titleCase(model.holdout_result)}</dd></div><div><dt>Consensus</dt><dd>{model.consensus_version ?? "Not applicable"}</dd></div><div><dt>Registered</dt><dd>{formatDateTime(model.created_at)}</dd></div></dl><div className="hash-line"><span>Registry hash</span><code>{model.registry_entry_hash}</code></div></Panel>)}</div> : <Panel><EmptyState icon={Activity} title="No registered models" body="The dashboard will not infer a fair-value authority without a retained registry entry." /></Panel>}
    {retained.length === 0 && <div className="warning-banner"><Ban /><div><strong>No retained benchmark registered</strong><span>Recommendations should remain unavailable until registry integrity is restored.</span></div></div>}
  </div>; }
