import { ArrowRight, Beaker, CheckCircle2, Database, LockKeyhole } from "lucide-react";
import { PageHeader, Panel, StatusBadge } from "../components/Primitives";

const phases = [
  { phase: "5B-1 / 2", title: "Corpus and point-in-time features", detail: "2014–2024 CFBD facts, immutable artifacts, leakage-safe feature factory.", state: "complete" },
  { phase: "5B-3 / 4", title: "Baselines and distributions", detail: "Chronological OOF models, push-aware probability calibration, residual diagnostics.", state: "complete" },
  { phase: "5B-5 / 6", title: "Strong challengers and preseason context", detail: "Controlled complexity and personnel ablations without opening the holdout.", state: "complete" },
  { phase: "5B-7", title: "Model versus market", detail: "Same-horizon consensus comparison on identical common cohorts.", state: "complete" },
  { phase: "5B-8 / 9", title: "Freeze and locked 2025 holdout", detail: "Total blend failed frozen gates; market consensus retained without retuning.", state: "failed" },
  { phase: "5B-10", title: "Registry and 2026 shadow", detail: "Immutable benchmark registration and prospective shadow contract.", state: "complete" },
];
export function ResearchPage() { return <div className="page-stack"><PageHeader eyebrow="Evidence trail" title="NCAAF research program" description="A compact view of the evidence behind the registered benchmark. Full immutable reports remain in the repository." />
  <div className="research-kpis"><div><Database /><strong>2014–2024</strong><span>Development corpus</span></div><div><LockKeyhole /><strong>2025</strong><span>One-time locked holdout</span></div><div><Beaker /><strong>2026</strong><span>Prospective shadow</span></div></div>
  <Panel title="Phase 5 timeline" eyebrow="Chronological evidence"><div className="research-timeline">{phases.map((item, index) => <div className="research-step" key={item.phase}><div className={`timeline-node ${item.state}`}><CheckCircle2 /></div><div><span>{item.phase}</span><h3>{item.title}</h3><p>{item.detail}</p></div>{index < phases.length - 1 && <ArrowRight className="timeline-arrow" />}</div>)}</div></Panel>
  <div className="dashboard-split"><Panel title="Data coverage" eyebrow="Authoritative research inputs"><ul className="evidence-list"><li><strong>8,277</strong><span>eligible FBS-vs-FBS development games per horizon</span></li><li><strong>1.696M</strong><span>normalized CFBD plays</span></li><li><strong>2020–2024</strong><span>full morning historical market cohort</span></li><li><strong>3 books</strong><span>initial supported execution universe</span></li></ul></Panel><Panel title="Holdout conclusion" eyebrow="Decision preserved"><div className="holdout-card"><StatusBadge tone="negative">Blend rejected</StatusBadge><h3>Market consensus remains the benchmark</h3><p>The constrained market/Ridge total blend failed the frozen 2025 promotion gates. No tuning or reinterpretation followed.</p></div></Panel></div>
  <Panel title="Source provenance" eyebrow="Traceable inputs"><div className="method-grid"><div><strong>Market data</strong><p>The Odds API snapshots, raw and normalized, exact timestamp provenance.</p></div><div><strong>Football facts</strong><p>CollegeFootballData immutable source manifests and normalized Parquet research artifacts.</p></div><div><strong>Decisions</strong><p>Versioned models, policies, freeze manifests, and append-only shadow predictions.</p></div></div></Panel></div>; }
