import { Activity, Ban, CheckCircle2, Database, LockKeyhole, Microscope, Settings } from "lucide-react";
import { ErrorPage, LoadingPage, PageHeader, Panel, StatusBadge } from "../components/Primitives";
import { useDashboard } from "../hooks/useDashboard";
import { currency, percent, titleCase } from "../utils/format";

const labels: Record<string, { group: string; format: "percent" | "currency" | "count" | "boolean" }> = {
  minimum_ev: { group: "Qualification", format: "percent" }, minimum_edge: { group: "Qualification", format: "percent" }, maximum_dispersion: { group: "Qualification", format: "percent" }, minimum_books: { group: "Qualification", format: "count" }, freshness_seconds: { group: "Qualification", format: "count" },
  kelly_fraction: { group: "Staking", format: "percent" }, minimum_stake: { group: "Staking", format: "currency" }, maximum_stake: { group: "Staking", format: "currency" }, unit_fraction: { group: "Staking", format: "percent" },
  maximum_core_bet_fraction: { group: "Exposure", format: "percent" }, maximum_opportunistic_bet_fraction: { group: "Exposure", format: "percent" }, maximum_daily_fraction: { group: "Exposure", format: "percent" }, maximum_game_fraction: { group: "Exposure", format: "percent" }, maximum_team_fraction: { group: "Exposure", format: "percent" }, maximum_market_fraction: { group: "Exposure", format: "percent" },
  reduced_risk_drawdown: { group: "Drawdown", format: "percent" }, paused_drawdown: { group: "Drawdown", format: "percent" }, bankroll_floor_fraction: { group: "Drawdown", format: "percent" },
  parlay_enabled: { group: "Parlay sleeve", format: "boolean" }, parlay_minimum_ev: { group: "Parlay sleeve", format: "percent" }, parlay_maximum_fraction: { group: "Parlay sleeve", format: "percent" }, parlay_daily_fraction: { group: "Parlay sleeve", format: "percent" },
};
export function SettingsPage() { const query = useDashboard(); if (query.isLoading) return <LoadingPage />; if (query.isError || !query.data) return <ErrorPage message={query.error?.message || "Settings unavailable"} retry={() => void query.refetch()} />; const entries = Object.entries(query.data.system.policies).filter(([key]) => key in labels); const groups = [...new Set(entries.map(([key]) => labels[key].group))]; const models = query.data.system.models; const funnel = query.data.watchlist.pricing_funnel; const funnelStages = ["games_analyzed", "observations_received", "supported_book_observations", "unsupported_book_observations", "snapshot_age_seconds", "provider_quote_age_median_seconds", "provider_quote_age_p90_seconds", "provider_quote_age_max_seconds", "eligible_observations", "exact_paired_book_markets", "comparable_market_groups", "calculable_candidate_sides", "positive_ev_candidates", "watchlist_candidates", "qualified_candidates", "pass_candidates"]; const topRejections = Object.entries(query.data.watchlist.rejection_counts).sort((left, right) => right[1] - left[1] || left[0].localeCompare(right[0])).slice(0, 6); return <div className="page-stack"><PageHeader eyebrow="System configuration" title="Settings" description="Authoritative risk policy, model registry, and methodology evidence in one operational surface." actions={<StatusBadge tone="neutral"><LockKeyhole size={13} />Read only</StatusBadge>} />
  <div className="settings-note"><Settings /><div><strong>Backend settings are authoritative</strong><span>Values are loaded from server configuration. This dashboard cannot silently change risk or qualification rules.</span></div></div>
  <div className="settings-grid">{groups.map((group) => <Panel key={group} title={group}><div className="setting-list">{entries.filter(([key]) => labels[key].group === group).map(([key, value]) => <div key={key}><div><strong>{titleCase(key)}</strong><small>{key}</small></div><output>{formatSetting(value, labels[key].format, key)}</output></div>)}</div></Panel>)}</div>
  <Panel title="System / Methodology" eyebrow="Registered fair-value authority"><div className="benchmark-content"><div className="benchmark-icon"><CheckCircle2 /></div><div><span className="eyebrow">Retained NCAAF v1 benchmark</span><h2>Market consensus supplies fair value</h2><p>Executable sportsbook price remains a separate input. Diagnostic or rejected football models cannot silently feed recommendations.</p></div><StatusBadge tone={models.some((model) => model.status === "retained_benchmark") ? "positive" : "negative"}>{models.some((model) => model.status === "retained_benchmark") ? "Registry active" : "Registry unavailable"}</StatusBadge></div><div className="model-grid methodology-models">{models.map((model) => <div className="model-card" key={`${model.model_id}-${model.version}`}><div className="model-card-top"><div className={`model-icon ${model.status}`}>{model.status === "rejected" ? <Ban /> : model.status === "diagnostic" ? <Microscope /> : <Activity />}</div><StatusBadge tone={model.status === "retained_benchmark" ? "positive" : model.status === "rejected" ? "negative" : "info"}>{titleCase(model.status)}</StatusBadge></div><h3>{model.model_id}</h3><p>{model.promotion_decision}</p><dl><div><dt>Version</dt><dd>{model.version}</dd></div><div><dt>Market</dt><dd>{titleCase(model.market_type)}</dd></div><div><dt>Family</dt><dd>{titleCase(model.model_family)}</dd></div><div><dt>Holdout</dt><dd>{titleCase(model.holdout_result)}</dd></div></dl><div className="hash-line"><span>Registry entry hash</span><code>{model.registry_entry_hash}</code></div></div>)}</div></Panel>
  <Panel title="Latest Pricing Funnel" eyebrow="Stored diagnostic state"><p className="panel-description">Read-only counts from the latest persisted decision for each upcoming UTC slate. Snapshot age is the hard live-data guard; provider quote age is reported separately. Navigation does not call the odds provider.</p><StatusBadge tone={query.data.watchlist.pricing_pipeline_status === "HEALTHY" ? "positive" : "negative"}>{query.data.watchlist.pricing_pipeline_status}</StatusBadge><div className="setting-list">{funnelStages.map((stage) => <div key={stage}><div><strong>{titleCase(stage)}</strong><small>{stage}</small></div><output>{funnel[stage] ?? 0}</output></div>)}</div>{topRejections.length > 0 && <><span className="eyebrow">Top rejection counts</span><div className="setting-list">{topRejections.map(([reason, count]) => <div key={reason}><div><strong>{titleCase(reason)}</strong><small>{reason}</small></div><output>{count}</output></div>)}</div></>}{query.data.watchlist.slates.map((slate) => <div className="holdout-card" key={slate.slate_date}><StatusBadge tone={slate.pricing_pipeline_status === "HEALTHY" ? "info" : "negative"}>{slate.weekday} · {slate.pricing_pipeline_status}</StatusBadge><h3>{slate.slate_date}</h3><p>{slate.games_analyzed} games · {slate.pricing_funnel.eligible_observations ?? 0} eligible observations · {slate.pricing_funnel.exact_paired_book_markets ?? 0} paired markets · {slate.pricing_funnel.calculable_candidate_sides ?? 0} calculable sides · {slate.pricing_funnel.positive_ev_candidates ?? 0} positive EV · {slate.watchlist_count} watchlist · {slate.qualified_recommendations} qualified</p></div>)}</Panel>
  <Panel title="Research evidence" eyebrow="Phase 5 provenance"><div className="research-kpis"><div><Database /><strong>2014–2024</strong><span>Development corpus</span></div><div><LockKeyhole /><strong>2025</strong><span>Locked holdout completed once</span></div><div><Microscope /><strong>2026</strong><span>Prospective shadow</span></div></div><div className="holdout-card"><StatusBadge tone="negative">Blend rejected</StatusBadge><h3>Market consensus retained after the locked holdout</h3><p>The constrained market/Ridge total blend failed frozen promotion gates. The decision is preserved; no post-holdout retuning occurred.</p></div></Panel></div>; }

function formatSetting(value: number | boolean, type: "percent" | "currency" | "count" | "boolean", key: string) { if (type === "boolean") return value ? "Enabled" : "Disabled"; if (type === "currency") return currency(Number(value)); if (type === "percent") return percent(Number(value), key === "parlay_maximum_fraction" ? 2 : 1); if (key === "freshness_seconds") return `${value}s`; return String(value); }
